In [10]:
# W3resource
# basic numpy
# Q12

import numpy as np
a=np.array([1, 3, 7, 105])
print(a)
print("Size of the memory occupied by the said array=")
print("%d bytes" % (a.size * a.itemsize))


[  1   3   7 105]
Size of the memory occupied by the said array=
16 bytes


In [13]:
# Q13

import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [14]:
# Q14

import numpy as np
array=np.arange(30,71)
print("Array of the integers from 30 to70 =")
print(array)

Array of the integers from 30 to70 =
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [15]:
# Q15

import numpy as np
array=np.arange(30,71,2)
print("Array of all the even integers from 30 to 70 =")
print(array) 

Array of all the even integers from 30 to 70 =
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [16]:
# Q16

import numpy as np
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
# Q17

import numpy as np
X = np.random.normal(0,1,1)
print("Random number between 0 and 1=")
print(X)

Random number between 0 and 1=
[0.60031717]


In [24]:
# Q18

import numpy as np
x= np.random.normal(0,1,15)
print("15 random numbers from a standard normal distribution=")
print(x)

15 random numbers from a standard normal distribution=
[ 0.06678326 -0.41758681  0.87365412 -1.22981319 -0.36109621  0.47577308
  0.40390157  0.32477934 -0.54165531 -0.33336665 -1.30592235 -0.25226882
 -1.05658145 -1.3016691   0.2981026 ]


In [28]:
# Q19

import numpy as np
x=np.arange(15,55)
print(x[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [29]:
# Q20

import numpy as np
x=np.arange(0,12)
y=x.reshape((3,4))
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [33]:
# Q21


import numpy as np
x=np.linspace(5,50,10)
print(x)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [34]:
# numpy array
# Q1

import numpy as np
print(np.__version__)

1.21.5


In [35]:
# Q2

import numpy as np
l = [12.23, 13.32, 100, 36.32]
print("Original List=",l)
a = np.array(l)
print("One-dimensional NumPy array= ",a)

Original List= [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array=  [ 12.23  13.32 100.    36.32]


In [36]:
# Q3

import numpy as np
x =  np.arange(2, 11)
Y=x.reshape(3,3)
print(Y)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [37]:
# Q4


import numpy as np
x = np.zeros(10)
print(x)
print("Update sixth value to 11")
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [38]:
# Q5

import numpy as np
x = np.arange(12, 38)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [44]:
# Q6

import numpy as np
import numpy as np
x = np.arange(12, 38)
print(x)
print("Reverse array:")
x = x[::-1]
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [45]:
# Q7

import numpy as np
a = [1, 2, 3, 4]
print(a)
x = np.asfarray(a)
print("Array converted to a float type=")
print(x)

[1, 2, 3, 4]
Array converted to a float type=
[1. 2. 3. 4.]


In [46]:
# Q8

import numpy as np
x=np.ones(25)
y=x.reshape(5,5)
y[1:4,1:4]=0
print(y)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [53]:
# Q9
import numpy as np 
a = np.ones((3, 3))
b = np.zeros((5, 5))
b[1:-1, 1:-1] = a
print(b)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [58]:
# Q10

import numpy as np
x=np.ones(64).reshape(8,8)
x[::2,::2]=0
x[1::2,1::2]=0
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [1]:
# NumPy Linear Algebra
# Q1

import numpy as np
c= np.array([[1,0],[0,1]])
d = np.array([[1,2],[3,4]])
print((c.dot(d)))


[[1 2]
 [3 4]]


In [3]:
#Q2

import numpy as np
c= np.array([[1,0],[0,1]])
d = np.array([[1,2],[3,4]])
result = np.outer(c, d)
print (result)


[[1 2 3 4]
 [0 0 0 0]
 [0 0 0 0]
 [1 2 3 4]]


In [6]:
# Q3

import numpy as np
c= np.array([[1,0],[0,1]])
d = np.array([[1,2],[3,4]])

result1 = np.cross(c, d)
result2 = np.cross(d,c)
print("cross product of the said two vectors(c, d):")
print(result1)
print("cross product of the said two vectors(d, c):")
print(result2)

cross product of the said two vectors(c, d):
[ 2 -3]
cross product of the said two vectors(d, c):
[-2  3]


In [9]:
# Q4

import numpy as np
from numpy import linalg as LA
a = np.array([[1, 0], [1, 2]])
print(a)
print("Determinant of the said 2-D array:")
print(np.linalg.det(a))




[[1 0]
 [1 2]]
Determinant of the said 2-D array:
2.0


In [10]:
# Q5

import numpy as np
a = np.array([1,2,3])
b = np.array([0,1,0])
print(a)
print(b)
result =  np.einsum("n,n", a, b)
print("Einstein’s summation convention of the said arrays:")
print(result)
x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)
print("Original Higher dimension:")
print(x)
print(y)
result = np.einsum("mk,kn", x, y)
print("Einstein’s summation convention of the said arrays:")
print(result)

[1 2 3]
[0 1 0]
Einstein’s summation convention of the said arrays:
2
Original Higher dimension:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Einstein’s summation convention of the said arrays:
[[ 24  27  30]
 [ 78  90 102]
 [132 153 174]]


In [11]:
# Q6

import numpy as np
a = np.array([1,2,5])
b = np.array([2,1,0])
print(a)
print(b)
result = np.inner(a, b)
print(result)
print("Inner product of the said vectors:")
x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)
print("Higher dimension arrays:")
print(x)
print(y)
result1 = np.inner(x, y)
print("Inner product of the said vectors:")
print(result1)

[1 2 5]
[2 1 0]
4
Inner product of the said vectors:
Higher dimension arrays:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Inner product of the said vectors:
[[ 14  23  32]
 [ 50  86 122]
 [ 86 149 212]]


In [12]:
# Q7

import numpy as np
m = np.mat("3 -2;1 0")
print("a\n", m)
w, v = np.linalg.eig(m) 
print( "Eigenvalues of the said matrix",w)
print( "Eigenvectors of the said matrix",v)

a
 [[ 3 -2]
 [ 1  0]]
Eigenvalues of the said matrix [2. 1.]
Eigenvectors of the said matrix [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [14]:
# Q8

import numpy as np
a = np.array([1,2,3])
b = np.array([0,1,0])
print(a)
print(b)
result =  np.kron(a, b)
print(result)
x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)
print("Original Higher dimension:")
print(x)
print(y)
result = np.kron(x, y)
print("Kronecker product  of the said arrays:")
print(result)

[1 2 3]
[0 1 0]
[0 1 0 0 2 0 0 3 0]
Original Higher dimension:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Kronecker product  of the said arrays:
[[ 0  0  0  3  4  5  6  8 10]
 [ 0  0  0  6  7  8 12 14 16]
 [ 0  0  0  9 10 11 18 20 22]
 [ 9 12 15 12 16 20 15 20 25]
 [18 21 24 24 28 32 30 35 40]
 [27 30 33 36 40 44 45 50 55]
 [18 24 30 21 28 35 24 32 40]
 [36 42 48 42 49 56 48 56 64]
 [54 60 66 63 70 77 72 80 88]]


In [15]:
# Q9

import numpy as np
from numpy import linalg as LA
a = np.array([[1, 0, -1], [0, 1, 0], [1, 0, 1]])
print(a)
print("The condition number of the said matrix:")
print(LA.cond(a))

[[ 1  0 -1]
 [ 0  1  0]
 [ 1  0  1]]
The condition number of the said matrix:
1.4142135623730951


In [16]:
# Q10

import numpy as np
v = np.arange(8)
result = np.linalg.norm(v)
print("Vector norm:")
print(result)
m = np.matrix('1, 2; 3, 4') 
result1 = np.linalg.norm(m)
print("Matrix norm:")
print(result1)



Vector norm:
11.832159566199232
Matrix norm:
5.477225575051661


In [27]:
# NumPy Random
# Q1

import numpy as np
x = np.random.normal(size=5)
print(x)

[ 0.78536374  2.26958135  0.14866003 -1.35902465  0.71896121]


In [24]:
# Q2

import numpy as np
x = np.random.randint(10, 30, 6)
print(x)

[19 18 10 23 28 20]


In [31]:
# Q3

import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.03693777 0.6089032  0.42963591]
  [0.5420533  0.99610717 0.27241661]
  [0.97573538 0.79279412 0.6337154 ]]

 [[0.10875838 0.48860709 0.85552284]
  [0.15207913 0.63608173 0.11731163]
  [0.14612191 0.11843183 0.14866972]]

 [[0.69666133 0.85956685 0.18100129]
  [0.83016295 0.21974887 0.34854924]
  [0.5182363  0.20257978 0.97820549]]]


In [32]:
# Q4

import numpy as np
x = np.random.random((5,5))
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

[[0.95349864 0.51634668 0.11669738 0.83764434 0.73383892]
 [0.73705147 0.06337298 0.17268049 0.28845366 0.73427233]
 [0.5667534  0.25234327 0.13318168 0.61949164 0.16830709]
 [0.38554121 0.89608643 0.60321738 0.43219611 0.53653377]
 [0.03331862 0.33945318 0.82276016 0.68117296 0.99420807]]
Minimum and Maximum Values:
0.03331861851430018 0.9942080676070054


In [33]:
# Q5

import numpy as np
x = np.random.rand(10, 4)
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
print(y)

[[0.65327385 0.04409263 0.48993355 0.56032244]
 [0.40139461 0.07312145 0.56144666 0.7032924 ]
 [0.18332577 0.95761685 0.63791433 0.45300125]
 [0.6994873  0.56907642 0.05142012 0.78786002]
 [0.76851098 0.2904252  0.53510135 0.15570314]
 [0.53430055 0.26502845 0.02373878 0.93761808]
 [0.17668922 0.38607583 0.32037447 0.56214139]
 [0.08879946 0.40919742 0.58269314 0.70619387]
 [0.13538587 0.06596472 0.66801911 0.50143077]
 [0.47186476 0.39902113 0.37018437 0.75009775]]
First 5 rows of the above array:
[[0.65327385 0.04409263 0.48993355 0.56032244]
 [0.40139461 0.07312145 0.56144666 0.7032924 ]
 [0.18332577 0.95761685 0.63791433 0.45300125]
 [0.6994873  0.56907642 0.05142012 0.78786002]
 [0.76851098 0.2904252  0.53510135 0.15570314]]


In [38]:
# Q6

import numpy as np
x = np.arange(10)
np.random.shuffle(x)
print(x)
print("Same result using permutation():")
print(np.random.permutation(10))

[4 1 0 2 3 7 6 8 5 9]
Same result using permutation():
[1 5 0 3 9 2 7 8 4 6]


In [39]:
# Q7

import numpy as np
x= np.random.random((3,3))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.21821634 0.04862385 0.21719361]
 [0.3618794  0.2313733  0.73467352]
 [0.65796593 0.35994455 0.14847905]]
After normalization:
[[0.24720147 0.         0.24571072]
 [0.45660768 0.26637933 1.        ]
 [0.88818946 0.45378741 0.14555098]]


In [40]:
# Q8

import numpy as np
x = np.random.random(10)
print(x)
x.sort()
print("Sorted array:")
print(x)

[0.91284092 0.58298223 0.98092172 0.92045691 0.31704275 0.59589967
 0.67592503 0.57013685 0.86517127 0.56108387]
Sorted array:
[0.31704275 0.56108387 0.57013685 0.58298223 0.59589967 0.67592503
 0.86517127 0.91284092 0.92045691 0.98092172]


In [41]:
# Q9

import numpy as np
x = np.random.uniform(1, 12, 5)
print(x)
v = 4
n = x.flat[np.abs(x - v).argmin()]
print(n)

[ 3.12161274  5.44402707  5.82993182  2.42850972 10.03245706]
3.1216127406800953


In [43]:
# Q10

import numpy as np
x = np.random.randint(0,3,5)
print("First array:")
print(x)
y = np.random.randint(0,3,5)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[2 1 0 0 0]
Second array:
[1 0 0 2 1]
Test above two arrays are equal or not!
False


In [1]:
# NumPy Sorting and Searching
# Q1

import numpy as np
a = np.array([[10,40],[30,20]])
print(a)
print("Sort the array along the first axis:")
print(np.sort(a, axis=0))
print("Sort the array along the last axis:")
print(np.sort(a))
print("Sort the flattened array:")
print(np.sort(a, axis=None))


[[10 40]
 [30 20]]
Sort the array along the first axis:
[[10 20]
 [30 40]]
Sort the array along the last axis:
[[10 40]
 [20 30]]
Sort the flattened array:
[10 20 30 40]


In [2]:
# Q2

import numpy as np
data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('ABDO', 5, 48.5), ('MOHAMED', 6, 52.5),('AHMED', 5, 42.10), ('RAMY', 5, 40.11)]
students = np.array(students_details, dtype=data_type)   
print(students)
print("Sort by height")
print(np.sort(students, order='height'))    


[(b'ABDO', 5, 48.5 ) (b'MOHAMED', 6, 52.5 ) (b'AHMED', 5, 42.1 )
 (b'RAMY', 5, 40.11)]
Sort by height
[(b'RAMY', 5, 40.11) (b'AHMED', 5, 42.1 ) (b'ABDO', 5, 48.5 )
 (b'MOHAMED', 6, 52.5 )]


In [5]:
# Q3


import numpy as np
data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('ABDO', 5, 48.5), ('MOHAMED', 6, 52.5),('AHMED', 5, 42.10), ('RAMY', 5, 40.11)]
students = np.array(students_details, dtype=data_type)   
print(students)
print("Sort by class, then height if class are equal:")
print(np.sort(students, order=['class','height']))    


[(b'ABDO', 5, 48.5 ) (b'MOHAMED', 6, 52.5 ) (b'AHMED', 5, 42.1 )
 (b'RAMY', 5, 40.11)]
Sort by class, then height if class are equal:
[(b'RAMY', 5, 40.11) (b'AHMED', 5, 42.1 ) (b'ABDO', 5, 48.5 )
 (b'MOHAMED', 6, 52.5 )]


In [6]:
# Q5

import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
print(student_id)
i = np.argsort(student_id)
print("Indices of the sorted elements of a given array:")
print(i)

[1023 5202 6230 1671 1682 5241 4532]
Indices of the sorted elements of a given array:
[0 3 4 6 1 5 2]


In [7]:
# Q6

import numpy as np
complex_num = [1 + 2j, 3 - 1j, 3 - 2j, 4 - 3j, 3 + 5j]
print(complex_num)
print(np.sort_complex(complex_num))

[(1+2j), (3-1j), (3-2j), (4-3j), (3+5j)]
[1.+2.j 3.-2.j 3.-1.j 3.+5.j 4.-3.j]


In [8]:
# NumPy Mathematics
# Q1

import numpy as np
print("Add:")
print(np.add(1.0, 4.0))
print("Subtract:")
print(np.subtract(1.0, 4.0))
print("Multiply:")
print(np.multiply(1.0, 4.0))
print("Divide:")
print(np.divide(1.0, 4.0))


Add:
5.0
Subtract:
-3.0
Multiply:
4.0
Divide:
0.25


In [9]:
# Q3

import numpy as np
x = np.arange(10)
print(x)
print("Division of the array inputs, element-wise:")
print(np.true_divide(x, 3))



[0 1 2 3 4 5 6 7 8 9]
Division of the array inputs, element-wise:
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]


In [10]:
# Q4

import numpy as np
x = [1., 2., 3., 4.]
print(x)
print("Largest integer smaller or equal to the division of the inputs:")
print(np.floor_divide(x, 1.5))

[1.0, 2.0, 3.0, 4.0]
Largest integer smaller or equal to the division of the inputs:
[0. 1. 2. 2.]


In [11]:
# Q5

import numpy as np
x = np.arange(7)
print(x)
print("First array elements raised to powers from second array, element-wise:")
print(np.power(x, 3))


[0 1 2 3 4 5 6]
First array elements raised to powers from second array, element-wise:
[  0   1   8  27  64 125 216]


In [12]:
# Q6

import numpy as np
x = np.arange(15)
print(x)
print("Element-wise remainder of division:")
print(np.remainder(x, 5))


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Element-wise remainder of division:
[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]


In [13]:
# Q7

import numpy as np
x = np.array([-10.2, 122.2, .20])
print(x)
print("Element-wise absolute value:")
print(np.absolute(x))

[-10.2 122.2   0.2]
Element-wise absolute value:
[ 10.2 122.2   0.2]


In [14]:
# Q8

import numpy as np
x = np.round([1.45, 1.50, 1.55])
print(x)
x = np.round([0.28, .50, .64], decimals=1)
print(x)
x = np.round([.5, 1.5, 2.5, 3.5, 4.5]) # rounds to nearest even value
print(x)

[1. 2. 2.]
[0.3 0.5 0.6]
[0. 2. 2. 4. 4.]


In [15]:
# Q9

import numpy as np
x = np.array([-.7, -1.5, -1.7, 0.3, 1.5, 1.8, 2.0])
print(x)
x = np.rint(x)
print("Round elements of the array to the nearest integer:")
print(x)

[-0.7 -1.5 -1.7  0.3  1.5  1.8  2. ]
Round elements of the array to the nearest integer:
[-1. -2. -2.  0.  2.  2.  2.]


In [16]:
# Q10

import numpy as np
x = np.array([-1.6, -1.5, -0.3, 0.1, 1.4, 1.8, 2.0])
print(x)
print("Floor values of the above array elements:")
print(np.floor(x))
print("Ceil values of the above array elements:")
print(np.ceil(x))
print("Truncated values of the above array elements:")
print(np.trunc(x))

[-1.6 -1.5 -0.3  0.1  1.4  1.8  2. ]
Floor values of the above array elements:
[-2. -2. -1.  0.  1.  1.  2.]
Ceil values of the above array elements:
[-1. -1. -0.  1.  2.  2.  2.]
Truncated values of the above array elements:
[-1. -1. -0.  0.  1.  1.  2.]


In [17]:
# Q11

import numpy as np
x = np.random.random((5,3))
print("First array:")
print(x)
y = np.random.random((3,2))
print("Second array:")
print(y)
z = np.dot(x, y)
print("Dot product of two arrays:")
print(z)

First array:
[[0.90312596 0.48331687 0.75244806]
 [0.87779447 0.4613074  0.63804799]
 [0.01931945 0.27345064 0.41795242]
 [0.20856293 0.9837035  0.45296603]
 [0.38082955 0.88824481 0.10444985]]
Second array:
[[0.70358854 0.81011778]
 [0.35145107 0.12638476]
 [0.85730077 0.12541765]]
Dot product of two arrays:
[[1.4503656  0.88709255]
 [1.32673214 0.84944161]
 [0.4680084  0.10262964]
 [0.88079426 0.3500956 ]
 [0.66966683 0.43387725]]


In [20]:
# NumPy Statistics
# Q1

import numpy as np
a = np.arange(4).reshape((2,2))
print(a)
print("Maximum value of the above flattened array:")
print(np.max(a))
print("Minimum value of the above flattened array:")
print(np.min(a))


[[0 1]
 [2 3]]
Maximum value of the above flattened array:
3
Minimum value of the above flattened array:
0


In [23]:
# Q2

import numpy as np
x = np.arange(4).reshape((2, 2))
print(x)
print("\nMaximum value along the second axis:")
print(np.max(x, 1))
print("Minimum value along the second axis:")
print(np.min(x, 1))

[[0 1]
 [2 3]]

Maximum value along the second axis:
[1 3]
Minimum value along the second axis:
[0 2]


In [26]:
# Q3

import numpy as np
x = np.arange(12).reshape((2, 6))
print("\nOriginal array:")
print(x)
r1 = np.amax(x, 1) - np.amin(x, 1)
print("\nDifference between the maximum and the minimum values of the said array:")
print(r1)



Original array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Difference between the maximum and the minimum values of the said array:
[5 5]


In [27]:
# Q4

import numpy as np
x = np.arange(12).reshape((2, 6))
print(x)
r1 = np.percentile(x, 80, 1)
print("\n80th percentile for all elements of the said array along the second axis:")
print(r1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

80th percentile for all elements of the said array along the second axis:
[ 4. 10.]


In [29]:
# Q5

import numpy as np
x = np.arange(14).reshape((2,7))
print(x)
r1 =  np.median(x)
print("\nMedian of said array:")
print(r1)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]]

Median of said array:
6.5


In [31]:
# Q7

import numpy as np
x = np.arange(6)
print(x)
r1 = np.mean(x)
print("\nMean: ", r1)
r1 = np.std(x)
print("\nstd: ", r1)
r1= np.var(x)
print("\nvariance: ", r1)

[0 1 2 3 4 5]

Mean:  2.5

std:  1.707825127659933

variance:  2.9166666666666665


In [35]:
# Q8

import numpy as np
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print(x)
print(y)
print("\nCovariance matrix of the said arrays:\n",np.cov(x, y))

[0 1 2]
[2 1 0]

Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]


In [34]:
# Q9

import numpy as np
x = np.array([0, 1, 3])
y = np.array([2, 4, 5])
print(x)
print(y)
print("\nCross-correlation of the said arrays:\n",np.cov(x, y))

[0 1 3]
[2 4 5]

Cross-correlation of the said arrays:
 [[2.33333333 2.16666667]
 [2.16666667 2.33333333]]


In [36]:
# Q10

import numpy as np
x = np.array([0, 1, 3])
y = np.array([2, 4, 5])
print(x)
print(y)
print("\nPearson product-moment correlation coefficients of the said arrays:\n",np.corrcoef(x, y))

[0 1 3]
[2 4 5]

Pearson product-moment correlation coefficients of the said arrays:
 [[1.         0.92857143]
 [0.92857143 1.        ]]


In [37]:
# NumPy DateTime
# Q1

import numpy as np
print("March, 2017")
print(np.arange('2017-03', '2017-04', dtype='datetime64[D]'))




March, 2017
['2017-03-01' '2017-03-02' '2017-03-03' '2017-03-04' '2017-03-05'
 '2017-03-06' '2017-03-07' '2017-03-08' '2017-03-09' '2017-03-10'
 '2017-03-11' '2017-03-12' '2017-03-13' '2017-03-14' '2017-03-15'
 '2017-03-16' '2017-03-17' '2017-03-18' '2017-03-19' '2017-03-20'
 '2017-03-21' '2017-03-22' '2017-03-23' '2017-03-24' '2017-03-25'
 '2017-03-26' '2017-03-27' '2017-03-28' '2017-03-29' '2017-03-30'
 '2017-03-31']


In [38]:
# Q2

import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2022-10-08
Today:  2022-10-09
Tomorrow:  2022-10-10


In [40]:
# Q3

import numpy as np
print("Number of days, February, 2020: ")
print(np.datetime64('2020-03-01') - np.datetime64('2020-02-01'))
print("Number of days, February, 2021: ")
print(np.datetime64('2021-03-01') - np.datetime64('2021-02-01'))
print("Number of days, February, 2022: ")
print(np.datetime64('2022-03-01') - np.datetime64('2022-02-01'))

Number of days, February, 2020: 
29 days
Number of days, February, 2021: 
28 days
Number of days, February, 2022: 
28 days


In [46]:
# Q5

import numpy as np
print("First Monday in May 2023:")
print(np.busday_offset('2023-05', 0, roll='forward', weekmask='Mon'))


First Monday in May 2023:
2023-05-01


In [47]:
# Q6

import numpy as np
print("Number of weekdays in March 2023:")
print(np.busday_count('2023-03', '2023-04'))

Number of weekdays in March 2023:
23


In [1]:
# NumPy String
# Q1

import numpy as np
x1 = np.array(['Python', 'PHP'], dtype=np.str)
x2 = np.array([' Java', ' C++'], dtype=np.str)
print(x1)
print(x2)
new_array = np.char.add(x1, x2)
print("new array:")
print(new_array)



['Python' 'PHP']
[' Java' ' C++']
new array:
['Python Java' 'PHP C++']


C:\Users\fifa\AppData\Local\Temp\ipykernel_10520\3140250063.py:5: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x1 = np.array(['Python', 'PHP'], dtype=np.str)
C:\Users\fifa\AppData\Local\Temp\ipykernel_10520\3140250063.py:6: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x2 = np.array([' Java', ' C++'], dtype=np.str)


In [2]:
# Q2

import numpy as np
x1 = np.array(['Python', 'PHP', 'Java', 'C++'], dtype=np.str)
print(x1)
new_array = np.char.multiply(x1, 3)
print("New array:")
print(new_array)

['Python' 'PHP' 'Java' 'C++']
New array:
['PythonPythonPython' 'PHPPHPPHP' 'JavaJavaJava' 'C++C++C++']


C:\Users\fifa\AppData\Local\Temp\ipykernel_10520\84001888.py:4: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x1 = np.array(['Python', 'PHP', 'Java', 'C++'], dtype=np.str)


In [4]:
# Q5

import numpy as np
x = np.array(['python exercises', 'PHP', 'java', 'C++'], dtype=np.str)
print(x)
r = np.char.join(" ", x)
print(r)


['python exercises' 'PHP' 'java' 'C++']
['p y t h o n   e x e r c i s e s' 'P H P' 'j a v a' 'C + +']


C:\Users\fifa\AppData\Local\Temp\ipykernel_10520\3145185497.py:4: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array(['python exercises', 'PHP', 'java', 'C++'], dtype=np.str)


In [5]:
# Q6

import numpy as np
x = np.array(['python exercises', 'PHP', 'java', 'C++'], dtype=np.str)
print(x)
encoded_char = np.char.encode(x, 'cp500')
decoded_char = np.char.decode(encoded_char,'cp500')
print("\nencoded =", encoded_char)
print("decoded =", decoded_char)

C:\Users\fifa\AppData\Local\Temp\ipykernel_10520\3669773589.py:4: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array(['python exercises', 'PHP', 'java', 'C++'], dtype=np.str)


['python exercises' 'PHP' 'java' 'C++']

encoded = [b'\x97\xa8\xa3\x88\x96\x95@\x85\xa7\x85\x99\x83\x89\xa2\x85\xa2'
 b'\xd7\xc8\xd7' b'\x91\x81\xa5\x81' b'\xc3NN']
decoded = ['python exercises' 'PHP' 'java' 'C++']


In [6]:
# Q7

import numpy as np
x = np.array([' python exercises ', ' PHP  ', ' java  ', '  C++'], dtype=np.str)
print("Original Array:")
print(x)
stripped = np.char.strip(x)
print("\nRemove the leading and trailing whitespaces: ", stripped)

Original Array:
[' python exercises ' ' PHP  ' ' java  ' '  C++']

Remove the leading and trailing whitespaces:  ['python exercises' 'PHP' 'java' 'C++']


C:\Users\fifa\AppData\Local\Temp\ipykernel_10520\2904229458.py:4: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array([' python exercises ', ' PHP  ', ' java  ', '  C++'], dtype=np.str)


In [7]:
# Q8

import numpy as np
x = np.array([' python exercises ', ' PHP  ', ' java  ', '  C++'], dtype=np.str)
print("Original Array:")
print(x)
lstripped_char = np.char.lstrip(x)
print("\nRemove the leading whitespaces : ", lstripped_char)

Original Array:
[' python exercises ' ' PHP  ' ' java  ' '  C++']

Remove the leading whitespaces :  ['python exercises ' 'PHP  ' 'java  ' 'C++']


C:\Users\fifa\AppData\Local\Temp\ipykernel_10520\644099296.py:4: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array([' python exercises ', ' PHP  ', ' java  ', '  C++'], dtype=np.str)


In [8]:
# Q9

import numpy as np
x = np.array([' python exercises ', ' PHP  ', ' java  ', '  C++'], dtype=np.str)
print("Original Array:")
print(x)
rstripped_char = np.char.rstrip(x)
print("\nRemove the trailing whitespaces : ", rstripped_char)


Original Array:
[' python exercises ' ' PHP  ' ' java  ' '  C++']

Remove the trailing whitespaces :  [' python exercises' ' PHP' ' java' '  C++']


C:\Users\fifa\AppData\Local\Temp\ipykernel_10520\1405908604.py:4: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array([' python exercises ', ' PHP  ', ' java  ', '  C++'], dtype=np.str)


In [9]:
# Q10

import numpy as np
x = np.array(['Python PHP Java C++'], dtype=np.str)
print("Original Array:")
print(x)
r = np.char.split(x)
print("\nSplit the element of the said array with spaces: ")
print(r)

Original Array:
['Python PHP Java C++']

Split the element of the said array with spaces: 
[list(['Python', 'PHP', 'Java', 'C++'])]


C:\Users\fifa\AppData\Local\Temp\ipykernel_10520\364596609.py:4: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array(['Python PHP Java C++'], dtype=np.str)
